import random
from datetime import datetime, timedelta
import os

OUT = 'basdar_movie_fixtures.sql'
random.seed(42)

first_names = ['Liam','Noah','Oliver','Elijah','James','William','Benjamin','Lucas','Henry','Alexander','Emma','Olivia','Ava','Sophia','Isabella','Mia','Amelia','Harper','Evelyn','Abigail']
last_names = ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin']
languages = ['English','Indonesian','Spanish','French','German','Japanese','Korean','Hindi','Portuguese','Italian','Mandarin','Arabic']
directors = ['A. Director','B. Director','C. Director','D. Director','E. Director','F. Director','G. Director']

def rand_date(start_year=1950, end_year=2005):
    start = datetime(start_year,1,1)
    end = datetime(end_year,12,31)
    return (start + timedelta(days=random.randint(0,(end-start).days))).date()

def rand_date_between(start_year=2020, end_year=2025):
    start = datetime(start_year,1,1)
    end = datetime(end_year,12,31)
    return (start + timedelta(days=random.randint(0,(end-start).days))).date()

lines = []
lines.append('-- Fixtures generated by generate_fixtures.py')
lines.append('USE `basdat_movie`;')
lines.append('\n')


pakets = [
    ('Basic', '4.99', '720p', 1),
    ('Standard', '9.99', '1080p', 2),
    ('Premium', '14.99', '4K', 4),
    ('Mobile', '2.99', '480p', 1),
    ('Family', '19.99', '4K', 6)
]
lines.append('-- Paket_Langganan')
for p in pakets:
    lines.append(f"INSERT INTO `Paket_Langganan` (`nama_paket`,`harga_bulanan`,`maks_resolusi`,`maks_perangkat`) VALUES ('{p[0]}',{p[1]},'{p[2]}',{p[3]});")
lines.append('\n')


genre_count = 150
genres = [f'Genre_{i+1}' for i in range(genre_count)]
lines.append('-- Genre')
for i,g in enumerate(genres,1):
    lines.append(f"INSERT INTO `Genre` (`genre_id`,`nama_genre`) VALUES ({i},'{g}');")
lines.append('\n')


konten_count = 300
konten = []
for i in range(1,konten_count+1):
    title = f'Content {i}'
    sinopsis = f'Sinopsis untuk {title}'
    tahun = random.randint(1980,2025)
    rating = random.choice(['G','PG','PG-13','R','18+'])
    if i <= 150:
        typ = 'Film'
    else:
        typ = 'Serial_TV'
    konten.append((title, sinopsis, tahun, rating, typ))

lines.append('-- Konten')
for c in konten:
    title = c[0].replace("'","''")
    lines.append(f"INSERT INTO `Konten` (`judul`,`sinopsis`,`tahun_rilis`,`rating_usia`,`type`) VALUES ('{title}','{c[1]}',{c[2]},'{c[3]}','{c[4]}');")
lines.append('\n')


lines.append('-- Film')
for i in range(150):
    title = konten[i][0].replace("'","''")
    durasi = random.randint(60,180)
    sutradara = random.choice(directors)
    lines.append(f"INSERT INTO `Film` (`judul`,`durasi`,`sutradara`) VALUES ('{title}',{durasi},'{sutradara}');")
lines.append('\n')


lines.append('-- Serial_TV')
for i in range(150,300):
    title = konten[i][0].replace("'","''")
    total_season = random.randint(1,8)
    lines.append(f"INSERT INTO `Serial_TV` (`judul`,`total_season`) VALUES ('{title}',{total_season});")
lines.append('\n')


lines.append('-- Episode')
ep_id = 0
for i in range(150,300):
    title = konten[i][0].replace("'","''")
    
    for ep in range(1,3):
        ep_id += 1
        judul_episode = f'Episode {ep} of {title}'.replace("'","''")
        sinopsis = f'Sinopsis {ep} dari {title}'
        durasi = random.randint(20,60)
        lines.append(f"INSERT INTO `Episode` (`judul_serial`,`nomor_season`,`nomor_urut_episode`,`judul_episode`,`sinopsis`,`durasi`) VALUES ('{title}',1,{ep},'{judul_episode}','{sinopsis}',{durasi});")
lines.append('\n')


lines.append('-- Aktor')
aktors = []
for i in range(150):
    fn = random.choice(first_names)
    ln = random.choice(last_names)
    name = f'{fn} {ln} {i+1}'
    aktors.append(name)
    dob = rand_date(1960,2000)
    country = random.choice(['USA','Indonesia','UK','Canada','Australia','France','Germany'])
    lines.append(f"INSERT INTO `Aktor` (`nama_lengkap`,`tanggal_lahir`,`negara_asal`) VALUES ('{name}','{dob}','{country}');")
lines.append('\n')


lines.append('-- Audio')
for c in konten:
    langs = random.sample(languages, k=random.randint(1,2))
    for l in langs:
        lines.append(f"INSERT INTO `Audio` (`judul_konten`,`bahasa_audio`) VALUES ('{c[0].replace("'","''")}','{l}');")
lines.append('\n')


lines.append('-- Subtitle')
for c in konten:
    langs = random.sample(languages, k=random.randint(1,2))
    for l in langs:
        lines.append(f"INSERT INTO `Subtitle` (`judul_konten`,`bahasa_subtitle`) VALUES ('{c[0].replace("'","''")}','{l}');")
lines.append('\n')


lines.append('-- Genre_Konten')
for idx,c in enumerate(konten,1):
    assigned = random.sample(range(1,genre_count+1), k=random.randint(1,3))
    for g in assigned:
        lines.append(f"INSERT INTO `Genre_Konten` (`judul_konten`,`genre_id`) VALUES ('{c[0].replace("'","''")}',{g});")
lines.append('\n')


lines.append('-- Kartu_Kredit')
cards = []
for i in range(150):
    num = ''.join(str(random.randint(0,9)) for _ in range(16))
    num = num + str(i%100).zfill(2)  
    num = num[:19]
    cards.append(num)
    jenis = random.choice(['Visa','Mastercard','Amex'])
    four = num[-4:]
    exp = rand_date_between(2023,2030)
    lines.append(f"INSERT INTO `Kartu_Kredit` (`nomor_kartu`,`jenis`,`empat_digit_nomor`,`tanggal_kadaluarsa`) VALUES ('{num}','{jenis}','{four}','{exp}');")
lines.append('\n')


lines.append('-- Pelanggan')
pelanggans = []
for i in range(150):
    email = f'user{i+1}@example.com'
    name = f'{random.choice(first_names)} {random.choice(last_names)}'
    dob = rand_date(1970,2002)
    paket = random.choice([p[0] for p in pakets])
    
    kartu = random.choice(cards) if random.random() < 0.7 else 'NULL'
    pelanggans.append((email, name))
    if kartu == 'NULL':
        lines.append(f"INSERT INTO `Pelanggan` (`email`,`nama_lengkap`,`tanggal_lahir`,`nama_paket`,`nomor_kartu`) VALUES ('{email}','{name}','{dob}','{paket}',NULL);")
    else:
        lines.append(f"INSERT INTO `Pelanggan` (`email`,`nama_lengkap`,`tanggal_lahir`,`nama_paket`,`nomor_kartu`) VALUES ('{email}','{name}','{dob}','{paket}','{kartu}');")
lines.append('\n')


lines.append('-- Profil')
profiles = []
for i,(email,name) in enumerate(pelanggans,1):
    prof_name = f'Profil{i}'
    cat = random.choice(['Anak','Remaja','Dewasa'])
    lines.append(f"INSERT INTO `Profil` (`email_pelanggan`,`nama`,`kategori_usia`) VALUES ('{email}','{prof_name}','{cat}');")
    profiles.append((email,prof_name))
lines.append('\n')


lines.append('-- Transaksi')
for i in range(150):
    tdate = rand_date_between(2021,2025)
    biaya = round(random.uniform(2.99,29.99),2)
    status = random.choice(['Berhasil','Menunggu','Gagal'])
    email = random.choice(pelanggans)[0]
    lines.append(f"INSERT INTO `Transaksi` (`tanggal_pembayaran`,`biaya_tagihan`,`status`,`email_pelanggan`) VALUES ('{tdate}',{biaya},'{status}','{email}');")
lines.append('\n')


lines.append('-- Peran')
peran_set = set()
for i in range(200):
    a = random.choice(aktors)
    c = random.choice(konten)[0]
    key = (a,c)
    if key in peran_set:
        continue
    peran_set.add(key)
    role = random.choice(['Lead','Supporting','Cameo','Guest'])
    lines.append(f"INSERT INTO `Peran` (`nama_aktor`,`judul_konten`,`peran`) VALUES ('{a}','{c.replace("'","''")}','{role}');")
lines.append('\n')


lines.append('-- Menonton')
mn_set = set()
for i in range(150):
    prof = random.choice(profiles)
    c = random.choice(konten)[0]
    key = (prof[0],prof[1],c)
    if key in mn_set:
        continue
    mn_set.add(key)
    waktu = datetime.now() - timedelta(days=random.randint(0,1000))
    posisi = random.randint(0, int( (random.randint(20,180)) ))
    lines.append(f"INSERT INTO `Menonton` (`email_pelanggan`,`nama_profil`,`judul_konten`,`waktu_terakhir`,`posisi_terakhir`) VALUES ('{prof[0]}','{prof[1]}','{c.replace("'","''")}','{waktu.strftime('%Y-%m-%d %H:%M:%S')}',{posisi});")
lines.append('\n')


lines.append('-- Rating')

r_set = set()
while len(r_set) < 150:
    prof = random.choice(profiles)
    c = random.choice(konten)[0]
    key = (prof[0],prof[1],c)
    if key in r_set:
        continue
    r_set.add(key)
    skor = random.randint(1,5)
    comment = f'Komentar untuk {c}'
    lines.append(f"INSERT INTO `Rating` (`email_pelanggan`,`nama_profil`,`judul_konten`,`skor`,`komentar`) VALUES ('{prof[0]}','{prof[1]}','{c.replace("'","''")}',{skor},'{comment}');")
lines.append('\n')


with open(OUT,'w') as f:
    f.write('\n'.join(lines))

print(f'Wrote {OUT} with approx {len(lines)} statements')
