"""
Utility to replace placeholder 'Lead' values in Peran inserts with more descriptive character roles.
Only updates lines where the role column is exactly 'Lead'. Other entries remain unchanged.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Tuple

PROJECT_ROOT = Path(__file__).parent
SQL_PATH = PROJECT_ROOT / "IF2040_Milestone3_K1_G11.sql"

# Map titles to canonical character names to replace the placeholder role.
TITLE_ROLE_MAP: Dict[str, str] = {
    # MCU & superheroes
    "Iron Man": "Tony Stark",
    "Iron Man 2": "Tony Stark",
    "Iron Man 3": "Tony Stark",
    "The Avengers": "Tony Stark",
    "Avengers: Age of Ultron": "Steve Rogers",
    "Avengers: Infinity War": "Thor",
    "Avengers: Endgame": "Bruce Banner",
    "Thor": "Thor",
    "Thor: The Dark World": "Thor",
    "Thor: Ragnarok": "Thor",
    "Captain America: The First Avenger": "Steve Rogers",
    "Captain America: The Winter Soldier": "Steve Rogers",
    "Captain America: Civil War": "Steve Rogers",
    "Black Panther": "T\'Challa",
    "Doctor Strange": "Stephen Strange",
    "Doctor Strange in the Multiverse of Madness": "Stephen Strange",
    "Spider-Man: Homecoming": "Peter Parker",
    "Spider-Man: Far From Home": "Peter Parker",
    "Spider-Man: No Way Home": "Peter Parker",
    "Ant-Man": "Scott Lang",
    "Ant-Man and the Wasp": "Scott Lang",
    "Black Widow": "Natasha Romanoff",
    "Shang-Chi and the Legend of the Ten Rings": "Xu Shang-Chi",
    "Eternals": "Sersi",
    "Captain Marvel": "Carol Danvers",
    "Guardians of the Galaxy": "Peter Quill",
    "Guardians of the Galaxy Vol. 2": "Peter Quill",
    "Guardians of the Galaxy Vol. 3": "Peter Quill",
    "Black Panther: Wakanda Forever": "Shuri",
    "Loki": "Loki",
    "WandaVision": "Wanda Maximoff",
    "Hawkeye": "Clint Barton",
    "Moon Knight": "Marc Spector",
    "She-Hulk: Attorney at Law": "Jennifer Walters",
    "The Falcon and the Winter Soldier": "Sam Wilson",
    "Daredevil": "Matt Murdock",
    "Jessica Jones": "Jessica Jones",
    "The Punisher": "Frank Castle",
    "Agents of S.H.I.E.L.D.": "Phil Coulson",
    "Luke Cage": "Luke Cage",
    "Iron Fist": "Danny Rand",
    "Secret Invasion": "Nick Fury",
    "What If...?": "Grandmaster",
    "Gotham": "Jim Gordon",
    "Titans": "Dick Grayson",
    "Doom Patrol": "Cliff Steele",
    "The Flash": "Barry Allen",
    "Arrow": "Oliver Queen",
    "DCs Legends of Tomorrow": "Sara Lance",
    "Smallville": "Clark Kent",
    # Big franchises / films
    "Inception": "Dom Cobb",
    "The Dark Knight": "Bruce Wayne",
    "The Dark Knight Rises": "Bruce Wayne",
    "Batman Begins": "Bruce Wayne",
    "Interstellar": "Cooper",
    "Dunkirk": "Tommy",
    "Tenet": "The Protagonist",
    "Oppenheimer": "J. Robert Oppenheimer",
    "Joker": "Arthur Fleck",
    "Titanic": "Jack Dawson",
    "Avatar": "Jake Sully",
    "Avatar: The Way of Water": "Jake Sully",
    "The Matrix": "Neo",
    "The Matrix Reloaded": "Neo",
    "The Matrix Revolutions": "Neo",
    "John Wick": "John Wick",
    "John Wick: Chapter 2": "John Wick",
    "John Wick: Chapter 3 - Parabellum": "John Wick",
    "John Wick: Chapter 4": "John Wick",
    "Mission: Impossible": "Ethan Hunt",
    "Mission: Impossible - Fallout": "Ethan Hunt",
    "Top Gun": "Pete \"Maverick\" Mitchell",
    "Top Gun: Maverick": "Pete \"Maverick\" Mitchell",
    "Gladiator": "Maximus Decimus Meridius",
    "The Godfather": "Michael Corleone",
    "The Godfather Part II": "Michael Corleone",
    "Pulp Fiction": "Vincent Vega",
    "Fight Club": "Tyler Durden",
    "Forrest Gump": "Forrest Gump",
    "The Shawshank Redemption": "Andy Dufresne",
    "Parasite": "Kim Ki-taek",
    "Train to Busan": "Seok-woo",
    "The Raid": "Rama",
    "The Raid 2": "Rama",
    "Gundala": "Sancaka",
    "Sri Asih": "Alana",
    "Pengabdi Setan": "Rini",
    "Pengabdi Setan 2: Communion": "Rini",
    "KKN di Desa Penari": "Nur",
    "Laskar Pelangi": "Bu Muslimah",
    "Habibie & Ainun": "B. J. Habibie",
    "Dilan 1990": "Dilan",
    "Dilan 1991": "Dilan",
    "Milea: Suara dari Dilan": "Dilan",
    "Ada Apa Dengan Cinta?": "Cinta",
    "Ada Apa Dengan Cinta? 2": "Cinta",
    "Cek Toko Sebelah": "Erwin",
    "Ngeri-Ngeri Sedap": "Pak Domu",
    "Mencuri Raden Saleh": "Piko",
    "The Big 4": "Topan",
    "Perempuan Tanah Jahanam": "Maya",
    "Satu Suro": "Adrian",
    "Sebelum Iblis Menjemput": "Alfie",
    "Ratu Ilmu Hitam": "Hanif",
    "Suzanna: Bernapas dalam Kubur": "Suzzanna",
    "My Sassy Girl": "The Girl",
    "Oldboy": "Oh Dae-su",
    "Memories of Murder": "Park Doo-man",
    "Minari": "Jacob Yi",
    "Decision to Leave": "Song Seo-rae",
    "Broker": "Sang-hyun",
    "Burning": "Lee Jong-su",
    "Extreme Job": "Chief Go",
    "Exit": "Yong-nam",
    "Along With the Gods: The Two Worlds": "Kim Ja-hong",
    "Along With the Gods: The Last 49 Days": "Gang-lim",
    "The Wailing": "Jong-goo",
    "I Saw the Devil": "Kim Soo-hyun",
    "A Taxi Driver": "Kim Man-seob",
    "Miracle in Cell No. 7": "Lee Yong-gu",
    "Harry Potter and the Sorcerers Stone": "Harry Potter",
    "Harry Potter and the Chamber of Secrets": "Harry Potter",
    "Harry Potter and the Prisoner of Azkaban": "Harry Potter",
    "Harry Potter and the Goblet of Fire": "Harry Potter",
    "Harry Potter and the Order of the Phoenix": "Harry Potter",
    "Harry Potter and the Half-Blood Prince": "Harry Potter",
    "Harry Potter and the Deathly Hallows: Part 1": "Harry Potter",
    "Harry Potter and the Deathly Hallows: Part 2": "Harry Potter",
    "Fantastic Beasts and Where to Find Them": "Newt Scamander",
    "Fantastic Beasts: The Crimes of Grindelwald": "Newt Scamander",
    "Fantastic Beasts: The Secrets of Dumbledore": "Newt Scamander",
    "The Lord of the Rings: The Fellowship of the Ring": "Frodo Baggins",
    "The Lord of the Rings: The Two Towers": "Frodo Baggins",
    "The Lord of the Rings: The Return of the King": "Frodo Baggins",
    "The Hobbit: An Unexpected Journey": "Bilbo Baggins",
    "The Hobbit: The Desolation of Smaug": "Bilbo Baggins",
    "The Hobbit: The Battle of the Five Armies": "Bilbo Baggins",
    "Pirates of the Caribbean: The Curse of the Black Pearl": "Jack Sparrow",
    "Pirates of the Caribbean: Dead Mans Chest": "Jack Sparrow",
    "Pirates of the Caribbean: At Worlds End": "Jack Sparrow",
    "Jurassic Park": "Alan Grant",
    "Jurassic World": "Owen Grady",
    "Jurassic World: Fallen Kingdom": "Owen Grady",
    "Jaws": "Martin Brody",
    "E.T. the Extra-Terrestrial": "Elliott",
    "Back to the Future": "Marty McFly",
    "Back to the Future Part II": "Marty McFly",
    "Back to the Future Part III": "Marty McFly",
    "Star Wars: Episode IV - A New Hope": "Luke Skywalker",
    "Star Wars: Episode V - The Empire Strikes Back": "Luke Skywalker",
    "Star Wars: Episode VI - Return of the Jedi": "Luke Skywalker",
    "Star Wars: Episode I - The Phantom Menace": "Obi-Wan Kenobi",
    "Star Wars: Episode II - Attack of the Clones": "Anakin Skywalker",
    "Star Wars: Episode III - Revenge of the Sith": "Anakin Skywalker",
    "Tougen Anki": "Maruo Ichinose",
    # Prestige and streaming series
    "Breaking Bad": "Walter White",
    "Better Call Saul": "Jimmy McGill",
    "Game of Thrones": "Daenerys Targaryen",
    "House of the Dragon": "Rhaenyra Targaryen",
    "Stranger Things": "Eleven",
    "The Witcher": "Geralt of Rivia",
    "The Mandalorian": "Din Djarin",
    "The Last of Us": "Joel Miller",
    "Peaky Blinders": "Thomas Shelby",
    "Sherlock": "Sherlock Holmes",
    "Dexter": "Dexter Morgan",
    "Homeland": "Carrie Mathison",
    "Westworld": "Dolores Abernathy",
    "True Detective": "Rust Cohle",
    "The Boys": "Billy Butcher",
    "Invincible": "Mark Grayson",
    "The Umbrella Academy": "Viktor Hargreeves",
    "Narcos": "Pablo Escobar",
    "Money Heist": "The Professor",
    "Dark": "Jonas Kahnwald",
    "Chernobyl": "Valery Legasov",
    "Black Mirror": "Cliff Stanfield",
    "Fargo": "Lester Nygaard",
    "Lost": "Jack Shephard",
    "Prison Break": "Michael Scofield",
    "24": "Jack Bauer",
    "The Office": "Michael Scott",
    "Friends": "Rachel Green",
    "How I Met Your Mother": "Ted Mosby",
    "Seinfeld": "Jerry Seinfeld",
    "Modern Family": "Jay Pritchett",
    "Brooklyn Nine-Nine": "Jake Peralta",
    "Parks and Recreation": "Leslie Knope",
    "Suits": "Harvey Specter",
    "House": "Gregory House",
    "Greys Anatomy": "Meredith Grey",
    "CSI: Crime Scene Investigation": "Gil Grissom",
    "NCIS": "Leroy Jethro Gibbs",
    "Criminal Minds": "Jason Gideon",
    "Law & Order: Special Victims Unit": "Olivia Benson",
    "Supernatural": "Dean Winchester",
    "Gotham": "Jim Gordon",
    "The Expanse": "James Holden",
    "Battlestar Galactica": "William Adama",
    "Firefly": "Malcolm Reynolds",
    "Fringe": "Olivia Dunham",
    "The Walking Dead": "Rick Grimes",
    "Fear the Walking Dead": "Madison Clark",
    "Hannibal": "Hannibal Lecter",
    "Vikings": "Ragnar Lothbrok",
    "Vikings: Valhalla": "Leif Erikson",
    "Black Sails": "Captain Flint",
    "Rome": "Lucius Vorenus",
    "Spartacus": "Spartacus",
    "Teen Wolf": "Scott McCall",
    "Riverdale": "Archie Andrews",
    "Lucifer": "Lucifer Morningstar",
    "Sense8": "Sun Bak",
    "Mr. Robot": "Elliot Alderson",
    "The Crown": "Queen Elizabeth II",
    "The Handmaids Tale": "June Osborne",
    "Yellowstone": "John Dutton",
    "Ozark": "Marty Byrde",
    "Mad Men": "Don Draper",
    "Boardwalk Empire": "Nucky Thompson",
    "Mare of Easttown": "Mare Sheehan",
    "Succession": "Logan Roy",
    "Severance": "Mark Scout",
    "Andor": "Cassian Andor",
    "Obi-Wan Kenobi": "Obi-Wan Kenobi",
    "Ahsoka": "Ahsoka Tano",
    "Star Trek: Discovery": "Michael Burnham",
    "Star Trek: Picard": "Jean-Luc Picard",
    "The Good Doctor": "Shaun Murphy",
    "This Is Us": "Jack Pearson",
    "The Mentalist": "Patrick Jane",
    "Person of Interest": "John Reese",
    "Elementary": "Sherlock Holmes",
    "His Dark Materials": "Lyra Silvertongue",
    "The Sandman": "Morpheus",
    "Love, Death & Robots": "Snow",
    "Arcane": "Vi",
    "Castlevania": "Trevor Belmont",
    "The Dragon Prince": "Callum",
    "Avatar: The Last Airbender": "Aang",
    "The Legend of Korra": "Korra",
    "Squid Game": "Seong Gi-hun",
    "Kingdom": "Lee Chang",
    "Crash Landing on You": "Ri Jeong-hyeok",
    "Goblin": "Kim Shin",
    "Descendants of the Sun": "Yoo Si-jin",
    "Itaewon Class": "Park Sae-ro-yi",
    "Vincenzo": "Vincenzo Cassano",
    "Reply 1988": "Choi Taek",
    "Signal": "Park Hae-young",
    "Hospital Playlist": "Lee Ik-jun",
    "My Mister": "Park Dong-hoon",
    "All of Us Are Dead": "Nam On-jo",
    "Sweet Home": "Cha Hyun-soo",
    "Extraordinary Attorney Woo": "Woo Young-woo",
    "Hellbound": "Jung Jin-soo",
    # Anime
    "Attack on Titan": "Eren Yeager",
    "Naruto": "Naruto Uzumaki",
    "Naruto Shippuden": "Naruto Uzumaki",
    "Bleach": "Ichigo Kurosaki",
    "One Piece": "Monkey D. Luffy",
    "Demon Slayer": "Tanjiro Kamado",
    "Jujutsu Kaisen": "Yuji Itadori",
    "My Hero Academia": "Izuku Midoriya",
    "Fullmetal Alchemist: Brotherhood": "Edward Elric",
    "Death Note": "Light Yagami",
    "Hunter x Hunter": "Gon Freecss",
    "Chainsaw Man": "Denji",
    "Tokyo Ghoul": "Ken Kaneki",
    "Sword Art Online": "Kirito",
    "Black Clover": "Asta",
    "Fairy Tail": "Natsu Dragneel",
    "Haikyuu!!": "Shoyo Hinata",
    "Blue Lock": "Yoichi Isagi",
    "Spy x Family": "Loid Forger",
    "Dr. Stone": "Senku Ishigami",
    "Mob Psycho 100": "Shigeo Kageyama",
    "Vinland Saga": "Thorfinn",
    # Local series
    "Layangan Putus": "Aris",
    "Gadis Kretek": "Dasiyah",
    "Tira": "Suci",
    "Turn On": "Andreas",
    "Wedding Agreement The Series": "Bian",
    "Virgin The Series": "Talita",
}

ROLE_FALLBACK = ["Supporting", "Antagonist", "Supporting", "Cameo"]

peran_pattern = re.compile(
    r"INSERT IGNORE INTO `Peran` VALUES \('(?P<actor>[^']*)'\s*,\s*'(?P<title>[^']*)'\s*,\s*'(?P<role>[^']*)'\);",
    re.MULTILINE,
)

def escape_sql(value: str) -> str:
    """Escape single quotes for SQL string literals."""
    return value.replace("'", "\\'")

def main() -> None:
    text = SQL_PATH.read_text(encoding="utf-8")
    total = 0
    updated = 0
    fallback_index = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal total, updated, fallback_index
        actor = match.group("actor")
        title = match.group("title")
        role = match.group("role")
        total += 1

        if role != "Lead":
            return match.group(0)

        mapped_role = TITLE_ROLE_MAP.get(title)
        if mapped_role is None:
            mapped_role = f"{ROLE_FALLBACK[fallback_index % len(ROLE_FALLBACK)]} ({actor.split()[0]})"
            fallback_index += 1

        updated += 1
        escaped_role = escape_sql(mapped_role)
        return f"INSERT IGNORE INTO `Peran` VALUES ('{actor}','{title}','{escaped_role}');"

    new_text = peran_pattern.sub(replace, text)

    if new_text == text:
        print("No changes applied.")
        return

    SQL_PATH.write_text(new_text, encoding="utf-8")
    print(f"Processed {total} Peran rows; updated {updated} placeholders.")


if __name__ == "__main__":
    main()
